# This is a basic workflow to help you get started with Actions

name: MM-TEST-ROBOT-ARM64-CACHE

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BRANCH: mm-unstable


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
    
      - uses: actions/cache@v4
        id: cache
        with:
          path: ../
          key: linux
    
      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd ..
          git clone https://github.com/ioworker0/ioworker0.git linux
          if git rev-parse --verify ${{ env.BRANCH }} >/dev/null 2>&1; then
            git branch -D ${{ env.BRANCH }}
          else
              echo "Branch ${{ env.BRANCH }} does not exist."
          fi
