# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BRANCH: lance
  REPO: https://github.com/ioworker0/linux.git

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          path: robot

      - name: system resources
        run: |      
          uname -r && uname -m && echo $(nproc) && free -h
          which clang

      # - uses: actions/cache@v4
      #   id: repo-cache
      #   with:
      #     path: .
      #     key: linux
    
      # - name: clone repo
      #   if: steps.repo-cache.outputs.cache-hit != 'true'
      #   run: |
      #     ls -l
      #     git clone -v ${{ env.REPO }} linux

      # - name: cc
      #   run: |
      #     git clone https://github.com/intel/lkp-tests.git lkp-tests
      #     mkdir build_dir && cp $(ls /boot/config-* | shuf -n 1) build_dir/.config
      #     COMPILER=clang lkp-tests/kbuild/make.cross W=1 O=build_dir olddefconfig
      #     COMPILER=clang lkp-tests/kbuild/make.cross W=1 O=build_dir SHELL=/bin/bash linux/
